### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by sascha-andres** [xrfang/restique#1]
Hi,

when I try to build using build.go I get this error:

```
panic: chdir /tmp/go-build961525851/command-line-arguments/_obj/exe/build: not a directory

goroutine 1 [running]:
main.assert(0x5472a0, 0xc4200164b0)
	/home/andres/projects/go/src/github.com/xrfang/restique/build.go:19 +0x4a
main.main()
	/home/andres/projects/go/src/github.com/xrfang/restique/build.go:249 +0x133
exit status 2
```

I am using go version 1.8.1 on linux/amd64

**Comment by xrfang** [comment]
Please do the following:

1. chmod +x build.go
2. ./build.go

Do not use `go run build.go` as the script relies on some trick to get the project directory.  I use this trick in my small project so that I don't need to write Makefile.
